CREATE TABLE chusan_matching_member
(
    id                     BIGINT AUTO_INCREMENT NOT NULL,
    user_id                BIGINT                NOT NULL,
    region_id              INT                   NOT NULL,
    place_id               INT                   NOT NULL,
    user_name              VARCHAR(255)          NOT NULL,
    player_rating          INT                   NOT NULL,
    battle_rank_id         INT                   NOT NULL,
    battle_correction      INT                   NOT NULL,
    battle_rating_avg      INT                   NOT NULL,
    opt_rating_id          INT                   NOT NULL,
    rating_effect_color_id INT                   NOT NULL,
    trophy_id              INT                   NOT NULL,
    nameplate_id           INT                   NOT NULL,
    emblem_medal           INT                   NOT NULL,
    emblem_base            INT                   NOT NULL,
    character_id           INT                   NOT NULL,
    character_rank         INT                   NOT NULL,
    skill_id               INT                   NOT NULL,
    skill_lv               INT                   NOT NULL,
    skill_id_for_chara     INT                   NOT NULL,
    is_join_team           BIT(1)                NOT NULL,
    team_name              VARCHAR(255)          NULL,
    team_rank              INT                   NOT NULL,
    message_id             INT                   NOT NULL,
    client_id              VARCHAR(255)          NULL,
    rom_version            VARCHAR(255)          NULL,
    data_version           VARCHAR(255)          NULL,
    err_cnt                INT                   NOT NULL,
    host_err_cnt           INT                   NOT NULL,
    join_time              INT                   NOT NULL,
    CONSTRAINT pk_chusan_matching_member PRIMARY KEY (id),
    CONSTRAINT unique_chusan_matching_member UNIQUE (user_id, user_name)
);